### ISSUE TITLE
Bungeecord / Waterfall Minecraft Proxies do not respond to standard `minecraft` queries

### ISSUE THREAD

**Issue by robbiek** [sonicsnes/node-gamedig#116] opened 2019-03-05 19:17 UTC
When querying a minecraft server i get the number of players online correctly put player data is empty

`{"name":"","map":"","password":false,"raw":{"version":{"name":"BungeeCord 1.8.x-1.13.x","protocol":404},"players":{"max":150,"online":1},"description":{"extra":[{"color":"red","text":"| "},{"color":"aqua","text":"exampleserver"},{"color":"red","text":"| "},{"color":"gold","text":"(1.13.2 BETA)"}],"text":""},"modinfo":{"type":"FML","modList":[]},"rcvNumPlayers":1},"maxplayers":150,"players":[{}],"bots":[],"connect":"play.example.net:25565","ping":40}`

Any ideas why this would be the case?

**Comment by sonicsnes** [comment] 2019-03-05 19:22
This is by design. Unfortunately, Minecraft does not provide full player
details (or even names). In some cases, it provides the names of only a
portion of the connected players, but in this case, it has not returned any
at all.

The 'raw' object contains everything we have received from the Minecraft
server ping, which doesn't include any names in your example.

**Comment by robbiek** [comment] 2019-03-05 19:58
Hi Sonicsnes thats for quick reply. I get data back from gameQ lib . i did find a solution. its to use the minecraftpe protocol.

**Comment by sonicsnes** [comment] 2019-03-05 20:04
Interesting, I'm surprised that works... I'll look into it more tonight. Is
this actually a Minecraftpe server? (Bedrock edition)

**Comment by robbiek** [comment] 2019-03-05 21:48
nope its 3 normal severs running 1.13 using bungeecord proxy. thanks.

**Comment by robbiek** [comment] 2019-03-05 21:50
this is the response when using minecractpe protocol 

`{"name":"examplename","map":"","password":false,"raw":{"playerTeamInfo":{"":[{"player":"Robbiek12"}]},"hostname":"examplename","gametype":"SMP","game_id":"MINECRAFT","version":"1.8.x-1.13.x","plugins":"","map":"BungeeCord_Proxy","numplayers":"1","maxplayers":"150","hostport":"25565","hostip":"0.0.0.0"},"maxplayers":150,"players":[{"name":"Robbiek12"}],"bots":[],"connect":"play.exampleserver.net:25565","ping":41}`

**Comment by sonicsnes** [comment] 2019-03-08 03:20
play.mcroyal.fr is a Waterfall Proxy, not a single minecraft server. It appears that Waterfall and Bungeecord have decided to implement the minecraft bedrock edition query protocol (gamespy3) rather than the standard minecraft query protocol.

Their query implementations are here:
https://github.com/SpigotMC/BungeeCord/blob/0dd538f9ff77c20da72c4530b3d21633799bc3a5/query/src/main/java/net/md_5/bungee/query/QueryHandler.java#L103
https://github.com/PaperMC/Waterfall/blob/7dd259045b14e6506bf9f48e63c164334faac445/BungeeCord-Patches/0031-Proxy-query-event.patch#L142

This is strange, but whatever. I suppose maybe we should just try both for all minecraft queries?

**Comment by robbiek** [comment] 2019-03-10 16:43
ah thank you. that explains it. will use bedrock protocol from now on.

**Comment by sustained** [comment] 2019-08-13 14:08
> This is by design. Unfortunately, Minecraft does not provide full player
details (or even names).

Well, I was just told by a PaperMC contributor and I quote:

> Minecraft and spigot will send all players. Paper will do the same.

So I'm a little confused here.

In any case, I can confirm that the PE/BE work around doesn't work for PaperMC servers.

Any insight into this? @sonicsnes 

[Relevant PaperMC issue](https://github.com/PaperMC/Paper/issues/2456)

**Comment by sonicsnes** [comment] 2019-10-16 05:01
This should be resolved in the latest version 2.0.15. We now just run a full gamespy3 AND minecraft ping against all minecraft servers, and merge the results.

**Closed by sonicsnes** 2019-10-16 05:01 UTC
Labels: enhancement

**Comment by sustained** [comment] 2019-10-16 16:19
Amazing. :smile:
